### ISSUE TITLE
Style login

### ISSUE THREAD

**Issue by viralS-tuanlv** [pqv2210/IgniteBTL3#3]
https://github.com/pqv2210/IgniteBTL3/blob/555d6a49e37807e7d400b715af045a2fa95ddfb3/App/Containers/LoginScreen.js#L141
Không nhất thiết phải cho image vào trong View như này, 1 mình thằng image có thể làm được như vậy, nên tối giản hóa hạn chế view lồng nhau khi không cần thiết

**Comment by pqv2210** [comment]
Nếu không cho Image vào View thì em không làm cho nó ra giữa màn hình được vì ScrollView nó ko có thuộc tính alignItems.
