### ISSUE TITLE
Tối ưu view Signup screen

### ISSUE THREAD

**Issue by viralS-tuanlv** [pqv2210/IgniteBTL3#7]
https://github.com/pqv2210/IgniteBTL3/blob/555d6a49e37807e7d400b715af045a2fa95ddfb3/App/Containers/SignUpScreen.js#L20
tương tự issue #3

**Comment by pqv2210** [comment]
Nếu không cho Image vào View thì em không làm cho nó ra giữa màn hình được vì ScrollView nó ko có thuộc tính alignItems.
